title: Battery Monitor
description: A utility tool, notifies user about charging, discharging and not charging state of the battery on Linux.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
